site_name: Jed's Peds Help Site
site_description: 'A guide to help you troubleshoot your new pedal build.'
site_author: 'Jed'
docs_dir: docs/
repo_name: 'sonosus/pedal-docs'
repo_url: 'https://github.com/sonosus/pedal-docs'
nav:
    - Home: index.md
theme:
  name: 'material'
